WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SQLBLANKLINES ON

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = SPATIUM;


/* =========================================
   MEMBER
   ========================================= */

CREATE TABLE MEMBER (
    MEM_ID              VARCHAR2(36) NOT NULL,
    MEM_NICK            VARCHAR2(15) NOT NULL,
    MEM_EMAIL           VARCHAR2(50) NOT NULL,
    MEM_PASS            VARCHAR2(60),
    MEM_BIR             VARCHAR2(10) NOT NULL,
    MEM_SEX             VARCHAR2(10) NOT NULL,
    MEM_IMG             BLOB,
    PROVIDER            VARCHAR2(10) DEFAULT 'LOCAL' NOT NULL,
    PROVIDER_USER_ID    VARCHAR2(50),

    CONSTRAINT PK_MEMBER
        PRIMARY KEY (MEM_ID),

    CONSTRAINT UQ_MEMBER_EMAIL
        UNIQUE (MEM_EMAIL),

    CONSTRAINT UQ_MEMBER_PROVIDER_USER
        UNIQUE (PROVIDER, PROVIDER_USER_ID)
);

COMMENT ON COLUMN MEMBER.MEM_SEX
IS '0: 남자, 1: 여자';

COMMENT ON COLUMN MEMBER.PROVIDER
IS 'LOCAL, GOOGLE, APPLE';

COMMENT ON COLUMN MEMBER.PROVIDER_USER_ID
IS 'Google sub 또는 Apple sub 저장용';


/* =========================================
   PROJECT
   ========================================= */

CREATE TABLE PROJECT (
    PROJ_CODE    VARCHAR2(36) NOT NULL,
    PROJ_MEM     VARCHAR2(36) NOT NULL,
    PROJ_NAME    VARCHAR2(50),
    PROJ_DATE    TIMESTAMP,

    CONSTRAINT PK_PROJECT
        PRIMARY KEY (PROJ_CODE),

    CONSTRAINT FK_MEMBER_TO_PROJECT
        FOREIGN KEY (PROJ_MEM)
        REFERENCES MEMBER (MEM_ID)
        ON DELETE CASCADE
);


/* =========================================
   FURNITURE
   ========================================= */

CREATE TABLE FURNITURE (
    FUR_CODE           VARCHAR2(50)  NOT NULL,
    FUR_MEM            VARCHAR2(36),
    FUR_NAME           VARCHAR2(100) NOT NULL,
    FUR_NAME_KR        VARCHAR2(100),
    FUR_CATEGORY       VARCHAR2(50)  NOT NULL,
    FUR_CATEGORY_KR    VARCHAR2(50)  NOT NULL,
    FUR_WIDTH          VARCHAR2(10)  NOT NULL,
    FUR_HEIGHT         VARCHAR2(10)  NOT NULL,
    FUR_DEPTH          VARCHAR2(10)  NOT NULL,
    FUR_PATH           VARCHAR2(500) NOT NULL,
    FUR_IS_DEFAULT     VARCHAR2(1)   DEFAULT '0' NOT NULL,
    FUR_IS_ACTIVE      VARCHAR2(1)   DEFAULT '1' NOT NULL,

    CONSTRAINT PK_FURNITURE
        PRIMARY KEY (FUR_CODE),

    CONSTRAINT FK_MEMBER_TO_FURNITURE
        FOREIGN KEY (FUR_MEM)
        REFERENCES MEMBER (MEM_ID)
        ON DELETE CASCADE,

    CONSTRAINT CK_FURNITURE_IS_DEFAULT
        CHECK (FUR_IS_DEFAULT IN ('0', '1')),

    CONSTRAINT CK_FURNITURE_IS_ACTIVE
        CHECK (FUR_IS_ACTIVE IN ('0', '1'))
);


/* =========================================
   ROOM
   ========================================= */

CREATE TABLE ROOM (
    ROOM_ID          VARCHAR2(36)  NOT NULL,
    ROOM_PROJ        VARCHAR2(36)  NOT NULL,
    ROOM_PATH        VARCHAR2(300) NOT NULL,
    ROOM_NAME        VARCHAR2(30),
    ROOM_AREA        VARCHAR2(10),
    ROOM_CREATED     TIMESTAMP,
    ROOM_MODIFIED    TIMESTAMP,

    CONSTRAINT PK_ROOM
        PRIMARY KEY (ROOM_ID),

    CONSTRAINT FK_PROJECT_TO_ROOM
        FOREIGN KEY (ROOM_PROJ)
        REFERENCES PROJECT (PROJ_CODE)
        ON DELETE CASCADE
);


/* =========================================
   REFRESH_TOKEN
   ========================================= */

CREATE TABLE REFRESH_TOKEN (
    TOKEN_ID      VARCHAR2(36) NOT NULL,
    MEM_ID        VARCHAR2(36) NOT NULL,
    TOKEN_HASH    VARCHAR2(64) NOT NULL,
    EXPIRES_AT    TIMESTAMP NOT NULL,
    REVOKED       NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_REFRESH_TOKEN
        PRIMARY KEY (TOKEN_ID),

    CONSTRAINT FK_MEMBER_TO_REFRESH_TOKEN
        FOREIGN KEY (MEM_ID)
        REFERENCES MEMBER (MEM_ID)
        ON DELETE CASCADE,

    CONSTRAINT CK_REFRESH_TOKEN_REVOKED
        CHECK (REVOKED IN (0, 1))
);

EXIT
